SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

USE `hoi`;

CREATE TABLE `doxes` (
  `id` int(11) NOT NULL,
  `activated` tinyint(1) NOT NULL DEFAULT 1,
  `name` varchar(500) NOT NULL,
  `alias` varchar(500) NOT NULL DEFAULT 'NOT SET',
  `born` varchar(500) NOT NULL DEFAULT 'NOT SET',
  `phone` varchar(500) NOT NULL DEFAULT 'NOT SET',
  `address` varchar(500) NOT NULL DEFAULT 'NOT SET',
  `family` varchar(500) NOT NULL DEFAULT 'NOT SET',
  `additional` varchar(1500) NOT NULL DEFAULT 'NOT SET',
  `creator_name` varchar(500) NOT NULL DEFAULT '[SYSTEM]'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `activated` tinyint(1) NOT NULL DEFAULT 1,
  `created` varchar(500) NOT NULL DEFAULT current_timestamp(),
  `username` varchar(45) NOT NULL,
  `password` varchar(65) NOT NULL,
  `role` varchar(500) NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE `doxes`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQUE` (`name`);

ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UNIQUE` (`username`);


ALTER TABLE `doxes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
